### ISSUE TITLE
default-2021.dwlt still tracked by remote repository

### ISSUE THREAD

**Issue by AnonymousFool** [Micky774/unity_project#13]
Despite the addition of `/UserSettings` to `.gitignore`, it looks like changes to `default-2021.dwlt` will be tracked until we `git rm --cached` it and push that as a change. However, according to [a popular stackoverflow answer](https://stackoverflow.com/a/1274447), it looks like that will remove the file from everyone's local machine once they pull that change.

To that end, I'm opening this as an issue for discussion. There are two things I want from you.
1. If you know an alternate way of getting this file off of our remote repository **without** deleting it from everyone's local repositories, please inform me.
2. In absence of an alternate method, I'd like you to please back up `default-2021.dwlt` on your local machines.

Once all of us provide the okay (due to either an alternate method being found or each of us backing up the file locally) I'll remove the file from the remote repository in main and propagate that change to all the branches off of main that I work on, and will work under the assumption that each of you will propagate the change to your branches.

**Comment by Micky774** [comment]
I believe `git update-index --skip-worktree <file>` should suffice.

See:
- https://stackoverflow.com/questions/1274057/how-do-i-make-git-forget-about-a-file-that-was-tracked-but-is-now-in-gitignore/1274447#1274447
- https://stackoverflow.com/questions/13630849/git-difference-between-assume-unchanged-and-skip-worktree/13631525#13631525

Best way forwards is probably to checkout a new branch and test the behavior after running the command

**Comment by AnonymousFool** [comment]
Alright, I'll make a new branch and do a bit of testing with it.

I saw that command, but I got the impression that it leaves a copy of the file on the remote repository, which isn't the end of the world since it's only about 26 KB, but given the choice I'd like that fiend **destroyed**.

**Comment by Micky774** [comment]
Quick question -- are we certain we _don't_ want this file tracked? It provides no actual value to have a shared, version-controlled instance of this file?

**Comment by AnonymousFool** [comment]
Yes, it's a Unity editor layout file. It tracks how big different parts of the window, like the scene editor, the game display, the asset hierarchy, etc. are. It's ridiculous to to track this, it will constantly be changing based on the preferences and priorities of each of us as unity developers, and tracking it just means that each of us will have to change our unity editor's layout to our preference every time we pull the latest change someone else made.

It's not a serious problem by any stretch, but it is **a problem**. The layout settings for someone working on animations in unity will be very different than someone working on playtesting, and we shouldn't have these layout settings on a main branch dictated almost entirely the context of the last pull request merged into it. It simply works better for each person to have completely independent local unity editor layout settings.

**Comment by AnonymousFool** [comment]
Also

> I believe `git update-index --skip-worktree <file>` should suffice.

I've now tested this. It makes all local adds and commits ignore the file, such that the local user who uses the command will no longer update the remote copy of the file. If we all use this, it does solve the problem of the file constantly being updated, though it will still exist in the remote repository.

It would not require a pull request or special branch for each of us to perform this command, as its effect carries over to all branches, and only a person who locally performs the command will be affected.

**Comment by JosriqueJotaro** [comment]
I just ran some testing and deleting `default-2021.dwlt` won't affect anything - it gets regenerated when you reopen the unity project on the unity hub. It seems that `git rm --cached` is the only reasonable solution.

**Comment by Micky774** [comment]
> I just ran some testing and deleting `default-2021.dwlt` won't affect anything - it gets regenerated when you reopen the unity project on the unity hub. It seems that `git rm --cached` is the only reasonable solution.

@AnonymousFool if you can confirm this then this would, indeed, be the best solution

**Comment by AnonymousFool** [comment]
> I just ran some testing and deleting `default-2021.dwlt` won't affect anything - it gets regenerated when you reopen the unity project on the unity hub. It seems that `git rm --cached` is the only reasonable solution.

Completely correct. It regenerates the file to some default layout settings that you can then futz with to your heart's content.

Removed the file on a new branch off main and then messed with my personal layout settings, and I can confirm that the file is no longer tracked upon being removed in this way, and there will be no major consequences to removing the file in this way. As such, I'll be opening a pull request to merge this branch into main.

**Comment by AnonymousFool** [comment]
See #14
